# Generated by Django 3.2.4 on 2021-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redcarpetuplmsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custloanid', models.CharField(max_length=20)),
                ('custfirstname', models.CharField(max_length=20)),
                ('custlastname', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('age', models.IntegerField(max_length=5)),
                ('agentserviced', models.CharField(max_length=20)),
                ('loanamount', models.IntegerField(max_length=10)),
                ('loantenure', models.IntegerField(max_length=5)),
                ('loanroi', models.IntegerField(max_length=5)),
                ('monthlyinterest', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'redcarpetuplmsdb',
            },
        ),
        migrations.CreateModel(
            name='redcarpetuploanrequestsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanrequestid', models.CharField(max_length=20)),
                ('loancustfirstname', models.CharField(max_length=20)),
                ('loancustlastname', models.CharField(max_length=20)),
                ('custdob', models.DateField(max_length=20)),
                ('custage', models.IntegerField(max_length=5)),
                ('requestedagent', models.CharField(max_length=20)),
                ('requestedloanamount', models.IntegerField(max_length=10)),
                ('requestedloantenure', models.IntegerField(max_length=5)),
                ('requestedloanroi', models.IntegerField(max_length=5)),
                ('calculatedloaninterest', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'redcarpetuploanrequestsdb',
            },
        ),
        migrations.CreateModel(
            name='usersdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('age', models.IntegerField(max_length=5)),
                ('usersrole', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('mobileno', models.IntegerField(max_length=15)),
                ('passwrd', models.CharField(max_length=20)),
                ('confirmpass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usersdb',
            },
        ),
    ]
