# Generated by Django 3.2.4 on 2021-07-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedCarpetUp_LMS', '0002_auto_20210707_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='loanamount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='loanroi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='loantenure',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='redcarpetuplmsdb',
            name='monthlyinterest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='calculatedloaninterest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='custage',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='custdob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='requestedloanamount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='requestedloanroi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='redcarpetuploanrequestsdb',
            name='requestedloantenure',
            field=models.CharField(max_length=5),
        ),
    ]
