# Generated by Django 3.2.4 on 2021-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedCarpetUp_LMS', '0004_usersdb_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='confirmpass',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='passwrd',
            field=models.CharField(max_length=200),
        ),
    ]
